checkpoint: ''
gupen_net: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    in_channels: 1
    out_channels: 14
cuda_devices: '0'
dataloader: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    test: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        batch_size: 1
        shuffle: true
    train: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        batch_size: 1
        drop_last: true
        shuffle: true
    validate: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        batch_size: 1
        drop_last: true
        shuffle: true
dataset: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    batch_size_dic: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        gupen: 4
    gupen: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        gupen_set:
          - CHN
        exclude_list:
          - CHNCXR_0059_0
          - CHNCXR_0178_0
          - CHNCXR_0228_0
          - CHNCXR_0267_0
          - CHNCXR_0295_0
          - CHNCXR_0310_0
          - CHNCXR_0285_0
          - CHNCXR_0276_0
          - CHNCXR_0303_0
        num_landmark: 14
        prefix: ../data/gupen
        sigma: 3
        size:
          - 512
          - 512
        use_abnormal: false
    loss_weights:
      - 1
    name_list:
      - gupen
display_freq: 2
epochs: 100
eval_freq: 2
gln: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    globalNet_params: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        dilations:
          - 1
          - 2
          - 5
          - 2
          - 1
        kernel_size: 3
        scale_factor: 0.25
    localNet: unet2d
gln2: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    globalNet_params: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        dilations:
          - 1
          - 2
          - 5
          - 2
          - 1
        kernel_size: 3
        scale_factor: 0.25
    localNet: unet2d
learning: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    adam: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        lr: 0.0001
        weight_decay: 0.0001
    bce: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        reduction: sum
    cycliclr: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        base_lr: 0.0001
        cycle_momentum: false
        max_lr: 0.01
        mode: triangular2
        step_size_down: 2000
        step_size_up: 2000
    l1: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        reduction: sum
    l2: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        reduction: sum
    loss: bce
    optim: adam
    scheduler: cycliclr
    steplr: !!python/object:model.utils.yamlConfig.EasyDict
      opt:
        gamma: 0.5
        step_size: 30
    use_scheduler: true
mix_step: 1
model: unet2d
run_dir: ../runs
run_name: GU2Net_runs
save_freq: 0
seed: 42
transform_params: !!python/object:model.utils.yamlConfig.EasyDict
  opt:
    angle: 2
    axis: 1
    flip_rate: 0
    offsets:
      - 10
      - 10
    rotate_rate: 0.1
    translate_rate: 0.1
use_background_channel: false
